bookmarks/bookmarks/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/',include('account.urls')),
    url(r'^images/', include('images.urls', namespace='images')),
]

#在这种方法中，Django开发服务器将会在开发时改变对多媒体文件的服务
#static()帮助函数最适合在开发环境中使用而不是在生产环境使用。绝对
#不要在生产环境中使用Django来服务你的静态文件
if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookmarks/images/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^create/$', views.image_create, name='create'),
    url(r'^detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.image_detail, name='detail'),
    url(r'^like/$', views.image_like, name='like'),
    url(r'^$', views.image_list, name='list'),
]

bookmarks/images/models.py
from django.db import models
from django.conf import settings

from django.utils.text import slugify
from django.core.urlresolvers import reverse
# Create your models here.


class Image(models.Model):
    #一个用户可以 post 多张图片， 但是每张图片只能由一个用户上传
    user = models.ForeignKey(settings.AUTH_USER_MODEL,related_name='images_created')
    title = models.CharField(max_length=200)
    #一个只包含字母、数字、下划线、和连字符的标签， 用于创建优美的 搜索引擎友好（SEO-friendly）的 URL
    slug = models.SlugField(max_length=200,blank=True)
    #url ： 这张图片的源 URL
    url = models.URLField()
    #image ： 图片文件
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    description = models.TextField(blank=True)
    # ForeignKey 字段或者带有 unique=True 的字段表明了一个索引的创建
    created = models.DateField(auto_now_add=True,db_index=True)
    #一个字段来保存喜欢这张图片的用户。我们需要一个多对多关系。
    #因为一个用户可能喜欢很多张图片，一张图片也可能被很多用户喜欢
    #ManyToMany 字段提供了一个多对多管理器,这个管理器使我们可以回溯相关联的对象比如： 
    #image.user_like.all() 或者从一个 user 中回溯，比如：user.images_liked.all()
    user_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                        related_name='images_liked',blank=True)
    #使用信号功能
    #total_likes 字段给每张图片存储被用户喜欢的总数
    total_likes = models.PositiveIntegerField(db_index=True,default=0)
    def __str__(self):
        return self.title
    def save(self,*args,**kwargs):
        if not self.slug:
            #使用了 Django 提供的 slugify() 函数在没有提供 slug 
            #字段时根据给定的图片标题自动生 slug
            self.slug = slugify(self.title)
            if not self.slug:
                self.slug = "undefined"
        super(Image,self).save(*args,**kwargs)

    def get_absolute_url(self): 
        return reverse('images:detail',args=(self.id,self.slug))
    
    class Meta:
        ordering = ('-created',)

bookmarks/images/forms.py
from django import forms
from .models import Image

from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify

class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title','url','description')
        #我们的用户不会在表单中直接为图片添加 URL
        #他们将会使用一个 JavaScropt 工具来从其他网站中选择一张图片然后我们的
        #表单将会以参数的形式接收这张图片的 URL
        #我们覆写 url 字段的默认控件（widget）为一个 HiddenInput 控件，这个控件将
        #会被渲染为属性是 type="hidden" 的 HTML 元素
        #用这个控件是因为我们不想让用户看见这个字段
        widgets={
            'url':forms.HiddenInput,
        }
    #通过使用以 clean_<fieldname> 形式
    #命名的方法来实现。这个方法会在你为一个表单实例执行 is_valid() 时执行
    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg','jpeg']
        extension = url.rsplit('.',1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given url does not match valid image extensions')
        return url
    #ModelForm 提供了一个 save() 方法来保存目前的模型实例到数据库中，并且返回一个对象
    #如果 commit 是 False ， save() 方法将会返回一个模型实例但是并不会把这个对象保存到数据库中
    def save(self, force_insert=False,force_update=False,commit=True):
        image = super(ImageCreateForm, self).save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = '{}.{}'.format(slugify(image.title),image_url.rsplit('.', 1)[1].lower())
        # 从给定的 URL 中下载图片
        response = request.urlopen(image_url)
        #使用 Python 的 urllib 模块来下载图片，然后调用 save() 方法把图片传递给一个
        #ContentFiel 对象，这个对象被下载的文件所实例化
        image.image.save(image_name,ContentFile(response.read()),save=False)
        if commit:
            image.save()
        return image

bookmarks/images/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ImageCreateForm
from django.views.decorators.http import require_POST

from django.shortcuts import get_object_or_404 
from .models import Image
from django.http import HttpResponse , JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.core.cache import cache
from django.utils.cache import get_cache_key

from actions.utils import create_action

# Create your views here.
@login_required
def image_create(request):
    """
    View for creating an Image using the JavaScript Bookmarklet.
    """
    if request.method == 'POST':
        # form is sent
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            # form data is valid
            cd = form.cleaned_data
            #如果这个表单是合法的，我们将新建一个 Image 实例
            new_item = form.save(commit=False)
            # assign current user to the item
            #我们将绑定当前用户（user）到一个新的 iamge 对象。这样我们就可以知道是谁上传了每一张图片
            new_item.user = request.user
            new_item.save()
            #活动流，一个用户给某张图片打上书签
            create_action(request.user, 'bookmarked image', new_item)
            messages.success(request, 'Image added successfully')
            # redirect to new created item detail view
            #使用 Django 的信息框架创建了一条上传成功的消息然后重定向用户到新图像的规范URL
            #我们没有在 Image 模型中实现 get_absolute_url() 方法，我们等会儿将编写它
            return redirect(new_item.get_absolute_url())
    else:
            # build form with data provided by the bookmarklet via GET
            form = ImageCreateForm(data=request.GET)
    return render(request, 'images/image/create.html', {'section': 'images','form': form})
    
def image_detail(request, id, slug): 
    image = get_object_or_404(Image, id=id, slug=slug) 
    return render(request, 'images/image/detail.html', {'section': 'images','image': image})


@login_required 
def image_list(request): 
    #images = Image.objects.all() #按默认排序获取图片（默认为时间倒序）
    images = Image.objects.order_by('-total_likes')
    paginator = Paginator(images, 16) 
    page = request.GET.get('page') 
    try: 
        images = paginator.page(page) 
    except PageNotAnInteger: 
        # If page is not an integer deliver the first page 
        images = paginator.page(1) 
    except EmptyPage: 
        if request.is_ajax(): 
            # If the request is AJAX and the page is out of range return an empty page 
            return HttpResponse('') 
        # If page is out of range deliver last page of results 
        images = paginator.page(paginator.num_pages) 
    #ajax has bug can not display  need debug
    #images = Image.objects.all() 
    if request.is_ajax():
        return render(request, 'images/image/list_ajax.html', {'section': 'images', 'images': images}) 
    return render(request, 'images/image/list.html', {'section': 'images', 'images': images})






#Django 同样也提供了 require_POST 装饰器来只允许 POST 请求
#一个可让你传递一组请求方法作为参数的 require_http_methods 装饰器
#使用 Django 提供的 JsonResponse 类来将给你定的对象转换为一个 JSON 输出
#这个类返回一个带有 application/json 内容类型的 HTTP 响应
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')
    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.user_like.add(request.user)
                #活动流，一个用户like了一个图片
                create_action(request.user, 'likes', image)
            else:
                image.user_like.remove(request.user)
            return JsonResponse({'status':'ok'})
        except:
            pass
    return JsonResponse({'status':'ko'})

bookmarks/images/templates/images/image/create.html
{% extends "base.html" %}
{% block title %}Bookmark an image{% endblock %}
{% block content %}
    <h1>Bookmark an image</h1>
    {% comment %}
    ![]({{ request.GET.url }})
    {% endcomment %}
    <img src="{{ request.GET.url }}"  height="300"/>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Bookmark it!">
    </form>
{% endblock %}

bookmarks/images/templates/images/image/detail.html
{% extends "base.html" %} 

{% block title %}{{ image.title }}{% endblock %} 
{% block content %} 
    <h1>{{ image.title }}</h1> 
    
    <a href="{{ image.image.url }}">
        <img src="{{ image.image.url }}"  height="500"/>
    </a>
    
    {% comment %}
    {% load thumbnail %}
    {% thumbnail image.image "300" as im %}
        <a href="{{ image.image.url }}">
            <img src="{{ im.url }}" height="360">
        </a>
    {% endthumbnail %}
    {% endcomment %}
    {% with total_likes=image.user_like.count users_like=image.user_like.all %}
    <div class="image-info">
        <div>
            <span class="count">
            <span class="total">{{ total_likes }}</span>
            like{{ total_likes|pluralize }}
            </span>
            <a href="{% url "images:like" %}" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
            {% if request.user not in users_like %}
                Like
            {% else %}
                Unlike
            {% endif %}
            </a>
        </div>
        {{ image.description|linebreaks }}
    </div>
    <div class="image-likes"> 
        {% for user in image.user_like.all %} 
            <div>
                {%comment%}
                {%endcomment%}
                <img src="{{ user.profile.photo.url }}" />
                <p>{{ user.first_name }}</p> 
            </div> 
        {% empty %} 
            Nobody likes this image yet. 
        {% endfor %} 
    </div> 
    {% endwith %} 
{% endblock %}

{% block domready %}
    $('a.like').click(function(e){
        e.preventDefault();
        $.post('{% url "images:like" %}',
            {
                id: $(this).data('id'),
                action: $(this).data('action')
            },
            function(data){
                //alert('a.like')
                if (data['status'] == 'ok')
                {
                    //alert('a.like')
                    var previous_action = $('a.like').data('action');
                    // toggle data-action
                    $('a.like').data('action', previous_action == 'like' ? 'unlike' : 'like');
                    // toggle link text
                    $('a.like').text(previous_action == 'like' ? 'Unlike' : 'Like');
                    // update total likes
                    var previous_likes = parseInt($('span.count .total').text());
                    $('span.count .total').text(previous_action == 'like' ? previous_likes + 1 : previous_likes - 1);
                }
        });
    });
{% endblock %}

bookmarks/images/templates/images/image/list.html
{% extends "base.html" %} 
{% block title %}Images bookmarked{% endblock %} 
{% block content %} 
    <h1>Images bookmarked</h1> 
    <div id="image-list"> 
        {% include "images/image/list_ajax.html" %} 
    </div> 
{% endblock %}


{% block domready %} 
    var page = 1;
    var empty_page = false; 
    var block_request = false; 
    $(window).scroll(function() { 
        var margin = $(document).height() - $(window).height() - 200; 
        if ($(window).scrollTop() > margin && empty_page == false && block_request == false) { 
            block_request = true; 
            page += 1; 
            $.get('?page=' + page, function(data) { 
                if(data == '') { 
                    empty_page = true; 
                } else { 
                    block_request = false; 
                    $('#image-list').append(data); 
                } 
            }); 
        } 
    }); 
{% endblock %}

bookmarks/images/templates/images/image/list_ajax.html
{% load thumbnail %} 

{% for image in images %} 
    <div class="image"> 
        <a href="{{ image.get_absolute_url }}"> 
            
            <img src="{{ image.image.url }}"  height="300"/>
            
            {% comment %}
            {% thumbnail image.image "300x300" crop="100%" as im %}
                <a href="{{ image.get_absolute_url }}">
                    <img src="{{ im.url }}" >
                </a>
            {% endthumbnail %}
            {% endcomment %}
            <span >
            <span class="total">{{ image.total_likes }}</span>
            likes
            </span>
        </a> 
        <div class="info"> 
            <a href="{{ image.get_absolute_url }}" class="title">{{ image.title }}</a> 
        </div> 
    </div> 
{% endfor %}